import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getSession } from "@/lib/authSession";
import { cookies, headers } from "next/headers";
import CookiesConsentBanner from "./components/CookiesConsentBanner";
import { myPrisma } from "@/lib/prisma";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  searchParams,
}: Readonly<{
  children: React.ReactNode;
  searchParams: { [key: string]: string | string[] | undefined };
}>) {
  // Si User est pas connecté, on regarde si il a vu cookiesBanner //
  // Si non on lui envoie le composant Banner avec le serv Action avec tout les infos dont ont a besoin //
  // Si oui on regarde si il a accepté Cookies Banner, si il a accepté on regarde si sa session est active //
  // Si elle est pas active User vient de se reconnecter //
  const session = await getSession();
  if (!session) {
    const c = await cookies();
    const h = await headers();
    const hasConsent = c.get("cookie_consent");
    const language = h.get("accept-language");
    const refere = h.get("referer");

    const utm_source = String(searchParams.utm_source);
    const utm_campaign = String(searchParams.utm_source);
    const utm_medium = String(searchParams.utm_source);

    if (!hasConsent) {
      <CookiesConsentBanner
        utm_medium={utm_medium}
        utm_campaign={utm_campaign}
        utm_source={utm_source}
        refere={refere}
        language={language}
      />;
    }

    // Si user a accepté les cookies, on regarde si il a deja une session, si non ont lui increment sont visitCount //
    if (hasConsent?.value === "true") {
      const visitorId = String(c.get("visitorId"));
      const sessionActive = c.get("session_active");
      if (sessionActive?.value === "true") {
        await myPrisma.anonymousVisitor.update({
          where: { visitorId },
          data: { visitCount: { increment: 1 } },
        });
      }
    }
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
