name: CI Socially

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installation des dépendances
        run: npm install

      - name: Génération du client Prisma
        run: npx prisma generate
        env:
          DIRECT_URL: ${{ secrets.DIRECT_URL }}

      - name: Vérification du Lint (ESLint)
        run: npm run lint

      - name: Génération des types Next.js
        run: npx next typegen

      - name: Vérification des types (TypeScript)
        run: npm run typecheck

      - name: Tentative de Build
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL}}
